IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'YieldData')
BEGIN
    CREATE TABLE YieldData (
        Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
        InstrumentName NVARCHAR(255) NOT NULL,
        Date DATE NOT NULL,
        Yield FLOAT NOT NULL,
        DateUpdated DATETIME DEFAULT GETDATE() NOT NULL
    )
END
